/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as PublicTermsIndexRouteImport } from './routes/_public/terms/index'
import { Route as PublicSignUpIndexRouteImport } from './routes/_public/sign-up/index'
import { Route as PublicSignInIndexRouteImport } from './routes/_public/sign-in/index'
import { Route as PublicPoliciesIndexRouteImport } from './routes/_public/policies/index'
import { Route as PublicOperationIndexRouteImport } from './routes/_public/operation/index'
import { Route as PublicGamesIndexRouteImport } from './routes/_public/games/index'
import { Route as PublicContactIndexRouteImport } from './routes/_public/contact/index'
import { Route as PublicHomeIndexRouteImport } from './routes/_public/_home/index'
import { Route as AppPatientsIndexRouteImport } from './routes/_app/patients/index'
import { Route as AppDashboardIndexRouteImport } from './routes/_app/dashboard/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTermsIndexRoute = PublicTermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignUpIndexRoute = PublicSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignInIndexRoute = PublicSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPoliciesIndexRoute = PublicPoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicOperationIndexRoute = PublicOperationIndexRouteImport.update({
  id: '/operation/',
  path: '/operation/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGamesIndexRoute = PublicGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactIndexRoute = PublicContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHomeIndexRoute = PublicHomeIndexRouteImport.update({
  id: '/_home/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AppPatientsIndexRoute = AppPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicHomeIndexRoute
  '/dashboard/': typeof AppDashboardIndexRoute
  '/patients/': typeof AppPatientsIndexRoute
  '/contact/': typeof PublicContactIndexRoute
  '/games/': typeof PublicGamesIndexRoute
  '/operation/': typeof PublicOperationIndexRoute
  '/policies/': typeof PublicPoliciesIndexRoute
  '/sign-in/': typeof PublicSignInIndexRoute
  '/sign-up/': typeof PublicSignUpIndexRoute
  '/terms/': typeof PublicTermsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicHomeIndexRoute
  '/dashboard': typeof AppDashboardIndexRoute
  '/patients': typeof AppPatientsIndexRoute
  '/contact': typeof PublicContactIndexRoute
  '/games': typeof PublicGamesIndexRoute
  '/operation': typeof PublicOperationIndexRoute
  '/policies': typeof PublicPoliciesIndexRoute
  '/sign-in': typeof PublicSignInIndexRoute
  '/sign-up': typeof PublicSignUpIndexRoute
  '/terms': typeof PublicTermsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/dashboard/': typeof AppDashboardIndexRoute
  '/_app/patients/': typeof AppPatientsIndexRoute
  '/_public/_home/': typeof PublicHomeIndexRoute
  '/_public/contact/': typeof PublicContactIndexRoute
  '/_public/games/': typeof PublicGamesIndexRoute
  '/_public/operation/': typeof PublicOperationIndexRoute
  '/_public/policies/': typeof PublicPoliciesIndexRoute
  '/_public/sign-in/': typeof PublicSignInIndexRoute
  '/_public/sign-up/': typeof PublicSignUpIndexRoute
  '/_public/terms/': typeof PublicTermsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/patients/'
    | '/contact/'
    | '/games/'
    | '/operation/'
    | '/policies/'
    | '/sign-in/'
    | '/sign-up/'
    | '/terms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/patients'
    | '/contact'
    | '/games'
    | '/operation'
    | '/policies'
    | '/sign-in'
    | '/sign-up'
    | '/terms'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/dashboard/'
    | '/_app/patients/'
    | '/_public/_home/'
    | '/_public/contact/'
    | '/_public/games/'
    | '/_public/operation/'
    | '/_public/policies/'
    | '/_public/sign-in/'
    | '/_public/sign-up/'
    | '/_public/terms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/terms/': {
      id: '/_public/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof PublicTermsIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-up/': {
      id: '/_public/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof PublicSignUpIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/sign-in/': {
      id: '/_public/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof PublicSignInIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/policies/': {
      id: '/_public/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PublicPoliciesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/operation/': {
      id: '/_public/operation/'
      path: '/operation'
      fullPath: '/operation/'
      preLoaderRoute: typeof PublicOperationIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/games/': {
      id: '/_public/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof PublicGamesIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact/': {
      id: '/_public/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof PublicContactIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/_home/': {
      id: '/_public/_home/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicHomeIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/patients/': {
      id: '/_app/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AppPatientsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard/': {
      id: '/_app/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
  AppPatientsIndexRoute: typeof AppPatientsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDashboardIndexRoute: AppDashboardIndexRoute,
  AppPatientsIndexRoute: AppPatientsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface PublicRouteChildren {
  PublicHomeIndexRoute: typeof PublicHomeIndexRoute
  PublicContactIndexRoute: typeof PublicContactIndexRoute
  PublicGamesIndexRoute: typeof PublicGamesIndexRoute
  PublicOperationIndexRoute: typeof PublicOperationIndexRoute
  PublicPoliciesIndexRoute: typeof PublicPoliciesIndexRoute
  PublicSignInIndexRoute: typeof PublicSignInIndexRoute
  PublicSignUpIndexRoute: typeof PublicSignUpIndexRoute
  PublicTermsIndexRoute: typeof PublicTermsIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicHomeIndexRoute: PublicHomeIndexRoute,
  PublicContactIndexRoute: PublicContactIndexRoute,
  PublicGamesIndexRoute: PublicGamesIndexRoute,
  PublicOperationIndexRoute: PublicOperationIndexRoute,
  PublicPoliciesIndexRoute: PublicPoliciesIndexRoute,
  PublicSignInIndexRoute: PublicSignInIndexRoute,
  PublicSignUpIndexRoute: PublicSignUpIndexRoute,
  PublicTermsIndexRoute: PublicTermsIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
